version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: node_modules/.bin/nodemon --exec npm start
    environment:
      NODE_ENV: development
    ports:
    - "3001:3001"
    links:
    - mongo
    volumes:
      - ./:/app
      - /app/node_modules
  mongo:
    image: mongo
    ports:
      - "27017:27017"
